# Generated by Django 5.1.4 on 2026-09-16 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('is_unlimited', models.BooleanField(default=False)),
                ('quota_sessions', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_days', models.PositiveSmallIntegerField()),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('branches', models.ManyToManyField(blank=True, related_name='subscription_types', to='tenants.branch')),
                ('directions', models.ManyToManyField(blank=True, related_name='subscription_types', to='tenants.direction')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTypeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('is_unlimited', models.BooleanField()),
                ('quota_sessions', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_days', models.PositiveSmallIntegerField()),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='subscriptions.subscriptiontype')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.AddConstraint(
            model_name='subscriptiontype',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_unlimited', True), ('quota_sessions__isnull', True)), models.Q(('is_unlimited', False), ('quota_sessions__isnull', False)), _connector='OR'), name='subscriptiontype_unlimited_xor_quota'),
        ),
    ]
