# Generated by Django 5.1.4 on 2026-09-17 06:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('subscriptions', '0001_initial'),
        ('tenants', '0003_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Активен'), ('expired', 'Истёк'), ('frozen', 'Заморожен'), ('exhausted', 'Исчерпан')], default='active', max_length=10)),
                ('sessions_remaining_cache', models.SmallIntegerField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='clients.child')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tenants.direction')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
                ('subscription_type_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptiontypeversion')),
            ],
            options={
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionFreeze',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freezes', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('initial_grant', 'Начисление при продаже'), ('consumption', 'Списание за посещение'), ('manual_adjustment', 'Ручная корректировка'), ('extension', 'Продление')], max_length=20)),
                ('delta', models.SmallIntegerField()),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
