# Generated by Django 5.1.4 on 2026-09-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('subscriptions', '0002_subscription_subscriptionfreeze_and_more'),
        ('tenants', '0003_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_comment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_reason',
            field=models.CharField(blank=True, choices=[('large_family', 'Многодетная семья'), ('second_child', 'Второй ребёнок'), ('promotion', 'Акция'), ('staff', 'Сотрудник'), ('other', 'Другое')], max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='list_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount', 0), models.Q(('discount_reason', ''), _negated=True), _connector='OR'), name='subscription_discount_requires_reason'),
        ),
    ]
