# Generated by Django 5.1.4 on 2026-09-17 10:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('subscriptions', '0003_subscription_discount_amount_and_more'),
        ('tenants', '0003_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonConsumption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('lesson_id', models.UUIDField()),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_consumptions', to='clients.child')),
                ('ledger_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='subscriptions.subscriptionledgerentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_consumptions', to='subscriptions.subscription')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('reverted_at__isnull', True)), fields=('child', 'lesson_id'), name='unique_active_consumption_per_child_lesson')],
            },
        ),
    ]
