# Generated by Django 5.1.4 on 2026-09-18 09:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_lessonconsumption'),
        ('tenants', '0003_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceDiscrepancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cached_value', models.SmallIntegerField(null=True)),
                ('recomputed_value', models.SmallIntegerField(null=True)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-found_at'],
            },
        ),
    ]
