# Generated by Django 5.1.4 on 2026-09-24 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_balancediscrepancy'),
        ('tenants', '0003_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tenants.branch'),
        ),
    ]
