# Generated by Django 5.1.4 on 2026-10-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_subscription_renewed_from_renewalcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
