# Generated by Django 5.1.4 on 2026-10-08 06:19

from django.db import migrations, models

# Так revert() подписывал откат до TRU-130 (kind=manual_adjustment).
REVERT_COMMENT_PREFIX = "Возврат по занятию "


def mark_old_reverts(apps, schema_editor):
    """TRU-130: прошлые откаты списания были записаны как ручная правка —
    переводим их в новый вид, чтобы отчёты различали их и по истории."""
    entry = apps.get_model("subscriptions", "SubscriptionLedgerEntry")
    entry.objects.filter(
        kind="manual_adjustment", delta=1, comment__startswith=REVERT_COMMENT_PREFIX
    ).update(kind="lesson_revert")


def unmark_old_reverts(apps, schema_editor):
    entry = apps.get_model("subscriptions", "SubscriptionLedgerEntry")
    entry.objects.filter(kind="lesson_revert").update(kind="manual_adjustment")


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0008_subscriptiontype_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionledgerentry",
            name="kind",
            field=models.CharField(
                choices=[
                    ("initial_grant", "Начисление при продаже"),
                    ("consumption", "Списание за посещение"),
                    ("manual_adjustment", "Ручная корректировка"),
                    ("extension", "Продление"),
                    ("lesson_revert", "Возврат занятия"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunPython(mark_old_reverts, unmark_old_reverts),
    ]
