# Generated by Django 5.1.4 on 2026-10-07 05:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_trial_children'),
        ('notifications', '0001_initial'),
        ('tenants', '0006_organization_ai_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.CharField(max_length=40)),
                ('channel', models.CharField(max_length=16)),
                ('language', models.CharField(max_length=5)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'event', 'channel', 'language'), name='message_template_unique')],
            },
        ),
        migrations.CreateModel(
            name='MessagingConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('utility', 'Служебные'), ('marketing', 'Рекламные')], max_length=16)),
                ('status', models.CharField(choices=[('opted_in', 'Согласен'), ('opted_out', 'Отписался')], max_length=16)),
                ('source', models.CharField(choices=[('admin_form', 'Отметил сотрудник (анкета, договор)'), ('parent_portal', 'Сам в кабинете'), ('unsubscribe_link', 'Ссылка «отписаться» в письме'), ('whatsapp_reply', 'Ответ «Стоп» в WhatsApp'), ('email_complaint', 'Жалоба на письмо')], max_length=24)),
                ('changed_at', models.DateTimeField()),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_consents', to='clients.parentcontact')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'parent', 'category'), name='messaging_consent_unique_parent_category')],
            },
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.CharField(max_length=40)),
                ('category', models.CharField(choices=[('utility', 'Служебные'), ('marketing', 'Рекламные')], max_length=16)),
                ('dedup_key', models.CharField(max_length=200)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('deferred', 'Ждёт утра (тихие часы)'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('failed', 'Не дошло'), ('no_consent', 'Нет согласия'), ('opted_out', 'Родитель отписался'), ('no_channel', 'Нет канала (нет email, WhatsApp не подключён)')], default='queued', max_length=16)),
                ('channel', models.CharField(blank=True, max_length=16)),
                ('recipient', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(blank=True, max_length=5)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('provider_id', models.CharField(blank=True, max_length=255)),
                ('attempts', models.JSONField(blank=True, default=list)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='clients.parentcontact')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'parent', '-created_at'], name='notificatio_organiz_f410d0_idx'), models.Index(fields=['organization', 'status', '-created_at'], name='notificatio_organiz_5e7163_idx'), models.Index(fields=['provider_id'], name='notificatio_provide_7d599e_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'dedup_key'), name='outbound_message_unique_dedup')],
            },
        ),
    ]
