# Generated by Django 5.1.4 on 2026-09-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cancelled_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
