# Generated by Django 5.1.4 on 2026-09-22 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_cancelled_reason'),
        ('subscriptions', '0005_balancediscrepancy'),
        ('tenants', '0003_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('manual', 'Ручная фиксация')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_raw_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждён'), ('rejected', 'Отклонён'), ('refunded', 'Возвращён')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('provider_transaction_id',), name='payment_unique_provider_transaction_id'),
        ),
    ]
