# Generated by Django 5.1.4 on 2026-10-01 06:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0012_trial_children"),
        ("payments", "0003_payment_confirmed_at_payment_provider_and_more"),
        ("subscriptions", "0007_subscription_renewed_from_renewalcontact"),
        ("tenants", "0003_direction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[("manual", "Ручная фиксация"), ("kaspi_pay", "Счёт Kaspi")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PaymentRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("phone", models.CharField(max_length=20)),
                ("amount", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "channel",
                    models.CharField(
                        choices=[("link", "Сообщение со ссылкой"), ("gateway", "Счёт в Kaspi")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("paid", "Оплачен"),
                            ("cancelled", "Отменён"),
                            ("expired", "Истёк"),
                            ("failed", "Не выставлен"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("pay_url", models.URLField(blank=True, max_length=500)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                ("provider_raw_response", models.JSONField(blank=True, default=dict)),
                ("idempotency_key", models.UUIDField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenants.organization"
                    ),
                ),
                (
                    "parent_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_requests",
                        to="clients.parentcontact",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="request",
                        to="payments.payment",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_requests",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status"], name="payments_pa_organiz_61c73b_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "idempotency_key"),
                        name="payment_request_unique_idempotency_key",
                    )
                ],
            },
        ),
    ]
