# Generated by Django 5.1.4 on 2026-10-02 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_payment_request"),
        ("payments", "0005_backfill_payment_payer"),
    ]

    operations = []
