# Generated by Django 5.1.4 on 2026-10-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_merge_20261002_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('manual', 'Ручная фиксация')], default='manual', max_length=20),
        ),
        migrations.DeleteModel(
            name='PaymentRequest',
        ),
    ]
