# Generated by Django 5.1.4 on 2026-10-08 07:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_remove_payment_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="paid_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
