# Generated by Django 5.1.4 on 2026-09-30 05:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metric', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=1, max_digits=14, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'metric', 'date'], name='analytics_m_organiz_4d2b9f_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'metric', 'branch', 'date'), name='unique_metric_snapshot_per_day', nulls_distinct=False)],
            },
        ),
    ]
