# Generated by Django 5.1.4 on 2026-09-17 10:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0004_communicationlog'),
        ('tenants', '0003_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='Вместимость')),
                ('age_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст от')),
                ('age_max', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст до')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('paused', 'Приостановлена'), ('closed', 'Закрыта')], default='active', max_length=16, verbose_name='Статус')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='tenants.branch', verbose_name='Филиал')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='tenants.direction', verbose_name='Направление')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
                ('teachers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, related_name='teaching_groups', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватели')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateField(verbose_name='Дата вступления')),
                ('left_at', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_memberships', to='clients.child', verbose_name='Ребёнок')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='groups.group', verbose_name='Группа')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Участие в группе',
                'verbose_name_plural': 'Участие в группах',
                'constraints': [models.UniqueConstraint(condition=models.Q(('left_at__isnull', True)), fields=('group', 'child'), name='unique_active_membership')],
            },
        ),
    ]
