# Generated by Django 5.1.4 on 2026-10-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_exclude_from_ai_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Показывать в публичном каталоге'),
        ),
    ]
