# Generated by Django 5.1.4 on 2026-10-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание для каталога'),
        ),
    ]
