# Generated by Django 5.1.4 on 2026-10-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='trial_available',
            field=models.BooleanField(default=True, verbose_name='Есть пробное занятие'),
        ),
        migrations.AddField(
            model_name='group',
            name='trial_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена пробного, ₸'),
        ),
    ]
