# Generated by Django 5.1.4 on 2026-09-25 06:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0011_importjob_decisions_and_rollback'),
        ('schedule', '0006_reschedule_call_log'),
        ('tenants', '0003_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Был'), ('absent', 'Не был'), ('makeup', 'Отработка')], max_length=16)),
                ('absence_reason', models.CharField(blank=True, choices=[('illness', 'Болезнь'), ('family', 'Семейные обстоятельства'), ('no_reason', 'Без причины')], default='', max_length=16)),
                ('consumed_from_subscription', models.BooleanField(default=False)),
                ('subscription_id', models.UUIDField(blank=True, null=True)),
                ('consume_outcome', models.CharField(blank=True, default='', max_length=32)),
                ('no_subscription_flag', models.BooleanField(default=False)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='clients.child')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='schedule.lesson')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('lesson', 'child'), name='unique_attendance_per_lesson_child')],
            },
        ),
    ]
