# Generated by Django 5.1.4 on 2026-09-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_retroactive_edit',
            field=models.BooleanField(default=False),
        ),
    ]
