# Generated by Django 5.1.4 on 2026-10-01 09:54

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='public_api_key',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='website_domain',
            field=models.CharField(blank=True, help_text='Домен сайта центра для формы приёма заявок (CORS), например https://trueballet.kz', max_length=255),
        ),
    ]
