# Generated by Django 5.1.4 on 2026-10-01 09:54

import secrets

from django.db import migrations, models


def fill_keys(apps, schema_editor):
    # default=uuid4 в AddField вычисляется один раз — у всех существующих
    # центров был бы один ключ, и unique-индекс не создавался бы.
    Organization = apps.get_model("tenants", "Organization")
    for organization in Organization.objects.all():
        organization.public_api_key = secrets.token_urlsafe(32)
        organization.save(update_fields=["public_api_key"])


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0003_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="public_api_key",
            field=models.CharField(default="", editable=False, max_length=64),
            preserve_default=False,
        ),
        migrations.RunPython(fill_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="organization",
            name="public_api_key",
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="website_domain",
            field=models.CharField(
                blank=True,
                help_text="Домен сайта центра для формы приёма заявок (CORS), например https://trueballet.kz",
                max_length=255,
            ),
        ),
    ]
