# Generated by Django 5.1.4 on 2026-10-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_normalize_public_api_key_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ai_enabled',
            field=models.BooleanField(default=True, help_text='ИИ-помощник включён (платная опция)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='ai_monthly_limit_kzt',
            field=models.PositiveIntegerField(blank=True, help_text='Лимит расхода ИИ в месяц, ₸. Пусто — лимит платформы по умолчанию.', null=True),
        ),
    ]
