# Generated by Django 5.1.4 on 2026-10-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_organization_ai_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='branch',
            name='coordinates_source',
            field=models.CharField(blank=True, choices=[('auto', 'По адресу'), ('manual', 'Вручную')], max_length=8),
        ),
        migrations.AddField(
            model_name='branch',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
