# Generated by Django 5.1.4 on 2026-09-21 05:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('schedule_templates', '0001_initial'),
        ('tenants', '0003_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(verbose_name='Начало')),
                ('ends_at', models.DateTimeField(verbose_name='Конец')),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('completed', 'Проведено'), ('cancelled', 'Отменено')], default='scheduled', max_length=16, verbose_name='Статус')),
                ('is_modified', models.BooleanField(default=False, help_text='True — администратор вручную изменил занятие. Такие занятия не пересоздаются при смене шаблона.', verbose_name='Изменено вручную')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='Причина отмены')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='groups.group', verbose_name='Группа')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='tenants.room', verbose_name='Зал')),
                ('schedule_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='schedule_templates.scheduletemplateslot', verbose_name='Слот шаблона')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taught_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['group', 'starts_at'], name='schedule_le_group_i_f463ab_idx'), models.Index(fields=['teacher', 'starts_at'], name='schedule_le_teacher_4ec590_idx'), models.Index(fields=['organization', 'starts_at'], name='schedule_le_organiz_979d53_idx')],
            },
        ),
    ]
