# Generated by Django 5.1.4 on 2026-09-21 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('schedule', '0001_initial'),
        ('schedule_templates', '0001_initial'),
        ('tenants', '0003_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='rescheduled_from',
            field=models.OneToOneField(blank=True, help_text='Исходное занятие при переносе', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='schedule.lesson', verbose_name='Перенесено из'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='ends_at',
            field=models.DateTimeField(verbose_name='Конец (UTC)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Null для индивидуального занятия', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='groups.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='starts_at',
            field=models.DateTimeField(verbose_name='Начало (UTC)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланировано'), ('completed', 'Проведено'), ('cancelled', 'Отменено'), ('rescheduled', 'Перенесено')], default='scheduled', max_length=16, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['organization', 'status', 'starts_at'], name='schedule_le_organiz_8c029c_idx'),
        ),
    ]
