# Generated by Django 5.1.4 on 2026-09-24 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('schedule', '0002_lesson_rescheduled_from_alter_lesson_ends_at_and_more'),
        ('schedule_templates', '0001_initial'),
        ('tenants', '0003_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['room', 'starts_at'], name='schedule_le_room_id_4aeb0d_idx'),
        ),
    ]
