# Generated by Django 5.1.4 on 2026-09-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_importjob_decisions_and_rollback'),
        ('schedule', '0003_lesson_room_starts_at_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='individual_children',
            field=models.ManyToManyField(blank=True, related_name='individual_lessons', to='clients.child', verbose_name='Дети (индивидуальное занятие)'),
        ),
    ]
