# Generated by Django 5.1.4 on 2026-09-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_lesson_individual_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='cancel_reason_category',
            field=models.CharField(blank=True, choices=[('teacher_illness', 'Болезнь преподавателя'), ('holiday', 'Праздник'), ('room_incident', 'Авария в помещении'), ('other', 'Другое')], max_length=32, verbose_name='Причина отмены (категория)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='cancel_reason',
            field=models.TextField(blank=True, verbose_name='Причина отмены (комментарий)'),
        ),
    ]
