# Generated by Django 5.1.4 on 2026-09-24 10:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_importjob_decisions_and_rollback'),
        ('schedule', '0005_lesson_cancel_reason_category'),
        ('tenants', '0003_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RescheduleCallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('called_at', models.DateTimeField(auto_now_add=True)),
                ('called_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_call_logs', to='schedule.lesson', verbose_name='Перенесённое занятие')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
                ('parent_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_call_logs', to='clients.parentcontact', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Отметка обзвона о переносе',
                'verbose_name_plural': 'Отметки обзвона о переносе',
                'constraints': [models.UniqueConstraint(fields=('lesson', 'parent_contact'), name='unique_reschedule_call_per_contact')],
            },
        ),
    ]
