# Generated by Django 5.1.4 on 2026-09-25 10:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_importjob_decisions_and_rollback'),
        ('schedule', '0006_reschedule_call_log'),
        ('tenants', '0003_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('makeup', 'Отработка'), ('trial', 'Пробное')], max_length=16)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_enrollments', to='clients.child')),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='schedule.lesson')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Запись поверх группы',
                'verbose_name_plural': 'Записи поверх группы',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True)), fields=('lesson', 'child'), name='unique_active_enrollment_per_lesson_child')],
            },
        ),
    ]
