# Generated by Django 5.1.4 on 2026-09-25 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_is_retroactive_edit'),
        ('clients', '0011_importjob_decisions_and_rollback'),
        ('schedule', '0007_lessonenrollment'),
        ('tenants', '0003_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonenrollment',
            name='source_attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makeup_enrollments', to='attendance.attendance'),
        ),
        migrations.AddConstraint(
            model_name='lessonenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True)), fields=('source_attendance',), name='unique_active_makeup_per_source_attendance'),
        ),
    ]
