# Generated by Django 5.1.4 on 2026-10-08 06:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_lead_campaigns'),
        ('schedule', '0011_alter_lessonenrollment_kind'),
        ('tenants', '0007_branch_city_branch_coordinates_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to='leads.lead')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to='schedule.lesson')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Бронь места',
                'verbose_name_plural': 'Брони мест',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lesson', 'expires_at'], name='schedule_se_lesson__5806ed_idx')],
            },
        ),
    ]
