# Generated by Django 5.1.4 on 2026-09-16 06:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10)),
                ('medical_notes', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('paused', 'Приостановлен'), ('left', 'Ушёл')], default='active', max_length=10)),
                ('leave_reason', models.TextField(blank=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('directions', models.ManyToManyField(blank=True, related_name='children', to='tenants.direction')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
