# Generated by Django 5.1.4 on 2026-09-16 07:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_parentcontact_contactphone'),
        ('tenants', '0003_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('mother', 'Мама'), ('father', 'Папа'), ('guardian', 'Опекун'), ('grandmother', 'Бабушка'), ('other', 'Другое')], max_length=20)),
                ('is_payer', models.BooleanField(default=False)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.child')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
                ('parent_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to='clients.parentcontact')),
            ],
            options={
                'ordering': ['child_id', '-is_primary_contact', 'role'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('child', 'parent_contact'), name='unique_active_child_parent_contact'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_payer', True)), fields=('child',), name='unique_active_payer_per_child'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_primary_contact', True)), fields=('child',), name='unique_active_primary_contact_per_child')],
            },
        ),
    ]
