# Generated by Django 5.1.4 on 2026-09-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_communicationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationlog',
            name='channel',
            field=models.CharField(choices=[('call', 'Звонок'), ('whatsapp', 'WhatsApp'), ('comment', 'Комментарий')], default='call', max_length=10),
        ),
    ]
