# Generated by Django 5.1.4 on 2026-09-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_communicationlog_channel'),
        ('tenants', '0003_direction'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='child',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'full_name'], name='child_org_full_name_idx'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'birth_date'], name='child_org_birth_date_idx'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'status'], name='child_org_status_idx'),
        ),
    ]
