# Generated by Django 5.1.4 on 2026-09-21 05:20

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_child_child_org_full_name_idx_and_more'),
        ('tenants', '0003_direction'),
        # gin_trgm_ops (opclass ниже) существует только после pg_trgm
        # (TrigramExtension) — без явной зависимости от этой миграции
        # порядок применения между независимыми приложениями не
        # гарантирован (см. core/migrations/0001_baseline.py), и на свежей
        # тестовой БД clients мог применяться раньше core.
        ('core', '0001_baseline'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='child',
            index=django.contrib.postgres.indexes.GinIndex(fields=['full_name'], name='child_full_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='contactphone',
            index=django.contrib.postgres.indexes.GinIndex(fields=['number'], name='cp_number_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='parentcontact',
            index=django.contrib.postgres.indexes.GinIndex(fields=['full_name'], name='pc_full_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='parentcontact',
            index=django.contrib.postgres.indexes.GinIndex(fields=['whatsapp'], name='pc_whatsapp_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
