# Generated by Django 5.1.4 on 2026-09-22 05:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_child_child_full_name_trgm_idx_and_more'),
        ('tenants', '0003_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('done', 'Готово'), ('failed', 'Ошибка')], default='pending', max_length=10)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('rows_payload', models.JSONField()),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('attached_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.JSONField(blank=True, default=list)),
                ('unhandled_balances', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportColumnMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('headers_key', models.CharField(max_length=1000)),
                ('file_headers', models.JSONField()),
                ('mapping', models.JSONField()),
                ('csv_delimiter', models.CharField(blank=True, max_length=4)),
                ('csv_encoding', models.CharField(blank=True, max_length=32)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'headers_key'), name='unique_active_mapping_per_headers')],
            },
        ),
    ]
