# Generated by Django 5.1.4 on 2026-09-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_importjob_importcolumnmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='error_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importjob',
            name='job_type',
            field=models.CharField(choices=[('dry_run', 'Сухой прогон'), ('execute', 'Импорт')], default='execute', max_length=10),
        ),
        migrations.AddField(
            model_name='importjob',
            name='ready_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importjob',
            name='report_rows',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='importjob',
            name='warning_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
