# Generated by Django 5.1.4 on 2026-09-24 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_importjob_error_count_importjob_job_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='executed_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_dry_run', to='clients.importjob'),
        ),
    ]
