# Generated by Django 5.1.4 on 2026-10-02 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpchallenge',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='portal.parentaccount'),
        ),
        migrations.AddField(
            model_name='otpchallenge',
            name='purpose',
            field=models.CharField(choices=[('login', 'Вход'), ('phone_change', 'Смена телефона')], default='login', max_length=20),
        ),
        migrations.AlterField(
            model_name='parentaccesslog',
            name='event',
            field=models.CharField(choices=[('code_requested', 'Запрошен код'), ('code_rate_limited', 'Слишком много запросов кода'), ('login', 'Вход'), ('login_failed', 'Неверный код'), ('logout', 'Выход'), ('logout_all', 'Выход на всех устройствах'), ('phone_changed', 'Сменил телефон')], max_length=30),
        ),
    ]
