# Generated by Django 5.1.4 on 2026-10-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_announcement_announcementread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentaccesslog',
            name='path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='parentaccesslog',
            name='event',
            field=models.CharField(choices=[('code_requested', 'Запрошен код'), ('code_rate_limited', 'Слишком много запросов кода'), ('login', 'Вход'), ('login_failed', 'Неверный код'), ('logout', 'Выход'), ('logout_all', 'Выход на всех устройствах'), ('phone_changed', 'Сменил телефон'), ('data_view', 'Смотрел данные')], max_length=30),
        ),
    ]
