# Generated by Django 5.1.4 on 2026-10-02 09:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_is_retroactive_edit'),
        ('clients', '0012_trial_children'),
        ('portal', '0004_parentaccesslog_path_alter_parentaccesslog_event'),
        ('schedule', '0010_trial_booking_changes'),
        ('tenants', '0003_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentLessonRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('enroll', 'Запись'), ('cancel', 'Отмена')], max_length=10)),
                ('kind', models.CharField(choices=[('regular', 'Обычное занятие'), ('makeup', 'Отработка')], default='regular', max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='new', max_length=12)),
                ('spots_available_at_request', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_lesson_requests', to='clients.child')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_requests', to='schedule.lesson')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_parent_lesson_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_requests', to='portal.parentaccount')),
                ('source_attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_makeup_requests', to='attendance.attendance')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status', '-created_at'], name='portal_pare_organiz_518bd1_idx'), models.Index(fields=['organization', 'child', '-created_at'], name='portal_pare_organiz_4f1fd9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'new')), fields=('organization', 'child', 'lesson', 'type', 'kind'), name='unique_open_parent_lesson_request'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('source_attendance__isnull', False), ('status', 'new')), fields=('organization', 'source_attendance'), name='unique_open_parent_makeup_source'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'makeup'), ('source_attendance__isnull', False), ('type', 'enroll')), models.Q(('kind', 'regular'), ('source_attendance__isnull', True)), _connector='OR'), name='valid_parent_request_source')],
            },
        ),
    ]
