# Generated by Django 5.1.4 on 2026-10-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0005_parentlessonrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="parentlessonrequest",
            name="cancel_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("illness", "Болезнь"),
                    ("family", "Семейные обстоятельства"),
                    ("other", "Другое"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="parentlessonrequest",
            name="notice_hours_required",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parentlessonrequest",
            name="notice_is_timely",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parentlessonrequest",
            name="will_be_charged",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
