# Generated by Django 5.1.4 on 2026-10-07 05:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_merge_0007_parentlessonrequest_rejection_reason_0007_parentnoteread'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentaccount',
            name='notification_prefs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='portal.parentaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
