# Generated by Django 5.1.4 on 2026-09-30 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_trial_children'),
        ('leads', '0009_rejection_reason_lost_contact'),
        ('tasks', '0001_initial'),
        ('tenants', '0003_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tenants.branch'),
        ),
        migrations.AddField(
            model_name='task',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='clients.child'),
        ),
        migrations.AddField(
            model_name='task',
            name='closing_comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.CharField(choices=[('manual', 'Вручную'), ('auto', 'Автоправило')], default='manual', max_length=16),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('trial_no_show', 'Не пришёл на пробное'), ('missing_subscription', 'Нет абонемента'), ('call_back', 'Перезвонить'), ('payment_reminder', 'Напомнить об оплате'), ('trial_signup', 'Записать на пробное'), ('renewal_offer', 'Предложить продление'), ('other', 'Другое')], default='other', max_length=32),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization', 'child', 'status'], name='tasks_task_organiz_9c62ad_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization', 'branch', 'status'], name='tasks_task_organiz_bda791_idx'),
        ),
    ]
