# Generated by Django 5.1.4 on 2026-10-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_retention_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('trial_no_show', 'Не пришёл на пробное'), ('missing_subscription', 'Нет абонемента'), ('retention', 'Удержание клиента'), ('parent_request', 'Запрос родителя'), ('other', 'Другое')], default='other', max_length=32),
        ),
    ]
