# Generated by Django 5.1.4 on 2026-10-01 07:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_trial_children'),
        ('leads', '0009_rejection_reason_lost_contact'),
        ('tasks', '0002_task_branch_task_child_task_closing_comment_and_more'),
        ('tenants', '0003_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rule', models.CharField(max_length=64)),
                ('tasks_created', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_automatic_task_source',
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('source_key', ''), _negated=True), ('deleted_at__isnull', True), ('status', 'open')), fields=('organization', 'type', 'source_key'), name='unique_automatic_task_source'),
        ),
        migrations.AddField(
            model_name='rulerun',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization'),
        ),
        migrations.AddIndex(
            model_name='rulerun',
            index=models.Index(fields=['organization', 'rule', 'created_at'], name='tasks_ruler_organiz_4f3c30_idx'),
        ),
    ]
