# Generated by Django 5.1.4 on 2026-10-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_retention_type'),
        ('tasks', '0003_rulerun_remove_task_unique_automatic_task_source_and_more'),
    ]

    operations = [
    ]
