# Generated by Django 5.1.4 on 2026-10-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_merge_20261002_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('trial_no_show', 'Не пришёл на пробное'), ('missing_subscription', 'Нет абонемента'), ('retention', 'Удержание клиента'), ('call_back', 'Перезвонить'), ('payment_reminder', 'Напомнить об оплате'), ('trial_signup', 'Записать на пробное'), ('renewal_offer', 'Предложить продление'), ('other', 'Другое')], default='other', max_length=32),
        ),
    ]
