# Generated by Django 5.1.4 on 2026-09-28 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_importjob_decisions_and_rollback'),
        ('leads', '0003_default_dictionaries'),
        ('tenants', '0003_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewal_leads', to='clients.child'),
        ),
        migrations.AddField(
            model_name='lead',
            name='kind',
            field=models.CharField(choices=[('new', 'Новая продажа'), ('renewal', 'Продление')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='leadrejectionreason',
            name='kind',
            field=models.CharField(choices=[('new', 'Новая продажа'), ('renewal', 'Продление')], default='new', max_length=10),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'kind', 'status'], name='leads_lead_organiz_82db06_idx'),
        ),
    ]
