# Generated by Django 5.1.4 on 2026-10-05 05:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_rejection_reason_lost_contact'),
        ('tenants', '0005_normalize_public_api_key_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadstatuschange',
            name='event_type',
            field=models.CharField(choices=[('status_change', 'Смена статуса'), ('trial_rescheduled', 'Пробное перенесено'), ('stage_change', 'Смена этапа')], default='status_change', max_length=24),
        ),
        migrations.CreateModel(
            name='LeadStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=60)),
                ('role', models.CharField(choices=[('new', 'Новая'), ('contacted', 'Связались'), ('trial_scheduled', 'Записан на пробное'), ('trial_attended', 'Пришёл на пробное'), ('purchased', 'Купил абонемент'), ('thinking', 'Думает'), ('rejected', 'Отказ')], max_length=20)),
                ('is_system', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('color', models.CharField(choices=[('blue', 'Синий'), ('red', 'Красный'), ('amber', 'Жёлтый'), ('violet', 'Фиолетовый'), ('green', 'Зелёный'), ('gray', 'Серый'), ('pink', 'Розовый'), ('teal', 'Бирюзовый')], default='gray', max_length=10)),
                ('is_hidden', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.leadstage'),
        ),
        migrations.AddField(
            model_name='leadstatuschange',
            name='to_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leads.leadstage'),
        ),
        migrations.AddConstraint(
            model_name='leadstage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True)), fields=('organization', 'role'), name='unique_system_stage_per_role'),
        ),
    ]
