# Generated by Django 5.1.4 on 2026-09-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('freeze', 'Заморозка'), ('unfreeze', 'Разморозка'), ('extend', 'Продление'), ('adjust', 'Корректировка'), ('grant', 'Выдача прав'), ('revoke', 'Отзыв прав'), ('cancel', 'Отмена'), ('reschedule', 'Перенос'), ('mark_attendance', 'Отметка посещаемости')], max_length=50),
        ),
    ]
