# Generated by Django 5.1.4 on 2026-10-07 10:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0001_initial'),
        ('tenants', '0006_organization_ai_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('photo_urls', models.JSONField(blank=True, default=list)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('is_published', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization',), name='center_profile_one_per_org')],
            },
        ),
    ]
