# Generated by Django 5.1.4 on 2026-10-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_ai_conversations'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='pseudonyms',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
