# Generated by Django 5.1.4 on 2026-10-06 10:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_airecommendationstate'),
        ('tenants', '0005_normalize_public_api_key_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneration',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='AIContentDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('kk', 'Қазақша')], max_length=2)),
                ('title', models.CharField(max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_content_drafts', to=settings.AUTH_USER_MODEL)),
                ('generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_drafts', to='ai.aigeneration')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['organization', 'language', '-updated_at'], name='ai_aiconten_organiz_097333_idx')],
            },
        ),
    ]
