# Generated by Django 5.1.4 on 2026-10-06 10:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_aiusage'),
        ('tenants', '0006_organization_ai_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDigest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('week_start', models.DateField()),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('running', 'Собирается'), ('ready', 'Готов'), ('insufficient_data', 'Данных пока мало'), ('limit_exhausted', 'Лимит исчерпан'), ('failed', 'Не собрался')], default='queued', max_length=32)),
                ('trigger', models.CharField(choices=[('schedule', 'По расписанию'), ('manual', 'Кнопка «Обновить»')], max_length=16)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('error_detail', models.CharField(blank=True, max_length=500)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status', '-created_at'], name='ai_aidigest_organiz_5deece_idx')],
            },
        ),
    ]
